# -*- coding: utf-8 -*-
"""감쇠자유진동_자동.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-1m7z4eMrFG8t4-Qzn4VvnkfNA9aRPCp
"""

import matplotlib.pyplot as plt
import numpy as np
from ipywidgets import interact, FloatSlider

# [기능 정의] 이 함수가 m, c, k를 받아서 그래프를 그려줍니다.
def plot_vibration(m, c, k, v_0):
    # 1. 계산
    c_cr = 2 * np.sqrt(k * m)
    lnn = c / c_cr

    # 부족감쇠(zeta < 1) 조건에서만 작동하도록 설정
    if lnn >= 1:
        print(f"⚠️ 현재 감쇠비가 {lnn:.2f}입니다. 과감쇠/임계감쇠 상태라 공식이 달라집니다!")
        return

    w_n = np.sqrt(k / m)
    w_d = w_n * np.sqrt(1 - lnn**2)
    x_0 = 0

    A = np.sqrt(((v_0 + lnn * w_n * x_0)**2 / (w_d**2)) + x_0**2)
    ppi = np.arctan((w_d * x_0) / (v_0 + lnn * w_n * x_0))

    t = np.linspace(0, 3, 1000)
    x = A * np.exp(-lnn * w_n * t) * np.sin(w_d * t + ppi)

    # 2. 그래프 출력
    plt.figure(figsize=(10, 5))
    plt.plot(t, x, lw=2, color='blue')
    plt.axhline(0, color='red', lw=1)
    plt.title(f"Vibration Result (Zeta: {lnn:.3f})")
    plt.grid(True)
    plt.ylim(-1.5, 1.5) # y축 고정해서 변화를 더 잘 보게 함
    plt.show()

# [앱 실행] 슬라이더와 입력창을 만듭니다.
interact(plot_vibration,
         m=FloatSlider(min=0.1, max=10.0, step=0.1, value=0.5, description='질량(m):'),
         c=FloatSlider(min=0.1, max=30.0, step=0.1, value=5.0, description='감쇠(c):'),
         k=FloatSlider(min=50, max=500, step=10, value=150, description='강성(k):'),
         v_0=FloatSlider(min=0.1, max=5.0, step=0.1, value=1.0, description='초기속도:'))
